# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a0e2f7fc7bf042b032fb4d1a515e9183447b4271f8736a8a2dccec33732b3bcbd46f29f7bd0163fe61e70c8acedb88289986c997bc691c19f7137545c78dda6

test:
  secret_key_base: 53b0fcfe52e3b14f2d7b50323336c0144a284a30a2be19cc7018d0897ccbb73615cc03f3a4a7d1a61bfb257f70c1f6dfba8c46f2d2a40e5171989e388f270876

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
